# Site settings
title: Agilead Website
email: contact@agilead.fr
description: > # this means to ignore newlines until "baseurl:"
  Agilead vise à vous accompagner pour amener vos équipes vers plus d'agilité. Au dela du dogme, par la pratique, en s'appuyant sur la capacité de vos équipes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://agilead.fr" # the base hostname & protocol for your site
twitter_username: jhattat
github_username:  jhattat

# Build settings
markdown: kramdown
